### ISSUE TITLE
sidenav auto closes.

### ISSUE THREAD

**Issue by nilipta** [dev-pranay/angular-sidenav-demo#1]
what to do if I want side-nav only collapses when I click the button, not anywhere else?

**Comment by dev-pranay** [comment]
Hi @nilipta , please refer the updated code.
The property '**disableClose**' on **mat-sidenav** is used to disable auto closing of sidenav. Please refer - https://material.angular.io/components/sidenav/overview#disabling-automatic-close
Also, you can remove the backdrop when sidenav is opened by using '**hasBackdrop**' property set to 'false' on **mat-sidenav-container**. Please refer - https://material.angular.io/components/sidenav/api#MatDrawerContainer
